### ISSUE TITLE
Aldonu PERMESILO.md-dosieron

### ISSUE THREAD

**Issue by nicolasmaia** [psychoslave/lupa#6]
Estus utila havi permesilan informon tuj videbla en la koddeponujo.

**Comment by psychoslave** [comment]
Certe. Kiel Lua mem, la kodaro uzas MIT pemisilon.

**Comment by psychoslave** [comment]
Farita!

**Comment by picsi** [comment]
Cetere, ĉu vi estas ĉe IRC/Matrix/Telegram? Se jes, alvoku min ĉe ##esperanto aŭ en telegramo.org :)

**Comment by nicolasmaia** [comment]
Cetere, ĉu vi estas ĉe IRC/Matrix/Telegram? Se jes, alvoku min ĉe ##esperanto aŭ en https://telegramo.org/ :)

**Comment by psychoslave** [comment]
En Freenode vi povas trovi mi kiel psychoslave, aŭ psychoslave_ au psychoslave__ ktp, depende de la fiagoj de mia IRBa programaro :P 

Mi ne konis telegramo ĝis nun, dankon por la ligo.
